#!/usr/bin/env bash
# 404 page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/new_404.html
sed -i "/server_name _/a error_page 404 /custom_404.html; \nlocation = /custom_404.html { \n root /var/www/html; \n internal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
