#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install -y haproxy=1.6.*

echo "frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend My_Web_Servers" >> /etc/haproxy/haproxy.cfg
echo "backend My_Web_Servers
    balance roundrobin
    server 2789-web-01 34.75.98.166:80 check
    server 2789-web-02 35.231.117.98 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
