#!/usr/bin/env bash
#script that displays: To infinity and beyond & I am invincible!!! indefinitely
trap "echo 'I am invincible!!!'" SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done