#!/usr/bin/env bash
# Runs nginx as nginx
sudo pkill -o apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i '4i\ user nginx; \n' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
