#!/usr/bin/env bash
# 7 lines or less
pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo nginx -c service nginx restart
